import type { Metadata } from "next";

import "./globals.css";
import { playfair, poppins } from "@/typography/fonts";
import Header from "@/components/layout/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${playfair.variable} bg-background text-foreground antialiased`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
